### ISSUE TITLE
Possible issue on Readme file

### ISSUE THREAD

**Issue by speeddragon** [belaustegui/trans#40]
Hi, I've found this library and I will be using soon. I was checking the Readme and found this code:

```
update table(:articles) do
      add :translations, :map
end 
```

Shouldn't be `alter table` instead `update table` ?

**Comment by belaustegui** [comment]
Sorry for the late reply, I missed the notification when this issue was opened.
You are completely right, I will update the README right now.

**Comment by belaustegui** [comment]
The PR #41 has just been created to address this issue.

**Comment by belaustegui** [comment]
PR has been merged, so I'm closing this issue.
Thank you again for the heads up @speeddragon !
